{
 "title": "Network Probe Monitor",
 "tags": [ "Skyline" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime,environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\"},host_name)"
    }
   },
   {
    "name": "d_namespace",
    "label": "Context:",
    "query": {
     "query": "label_values(system_uptime{host_name=~\"$d_hostname\", environment=~\"$d_environment\"}, service_namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Connectivity Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probe Protocol",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (last_over_time(network_probes_mode{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 1)",
     "legendFormat": "Direct ICMP"
    },
    {
     "expr": "count (last_over_time(network_probes_mode{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 3)",
     "legendFormat": "HTTP(s)"
    },
    {
     "expr": "count (last_over_time(network_probes_mode{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 2)",
     "legendFormat": "Spoofed ICMP"
    }
   ]
  },
  {
   "title": "Probe State",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 0)",
     "legendFormat": "Down"
    },
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 1)",
     "legendFormat": "Up"
    },
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == -1)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Number of Probes (Up/Down)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 0)",
     "legendFormat": "Down"
    },
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == 1)",
     "legendFormat": "Up"
    },
    {
     "expr": "count (last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]) == -1)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Probe Monitoring",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_join(last_over_time(network_probes_state{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]), \"prob_key\", \"_\", \"host_name\", \"context\", \"id\")"
    },
    {
     "expr": "label_join(last_over_time(network_probes_mode{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]), \"prob_key\", \"_\", \"host_name\", \"context\", \"id\")"
    },
    {
     "expr": "label_join(last_over_time(network_probes_last_probe{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s])*1000, \"prob_key\", \"_\", \"host_name\", \"context\", \"id\")"
    },
    {
     "expr": "label_join(last_over_time(network_probes_last_status_change{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s])*1000, \"prob_key\", \"_\", \"host_name\", \"context\", \"id\")"
    },
    {
     "expr": "label_join(last_over_time(vpn_probes_tunnel{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}[30s]), \"prob_key\", \"_\", \"host_name\", \"context\", \"id\")"
    }
   ]
  }
 ]
}